name: conso_customer
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  device_preview: ^0.7.3
  bot_toast: ^3.0.0
  dio: ^4.0.0
  url_launcher: ^5.4.11
  flutter_phone_direct_caller: ^1.0.1
  image_picker: ^0.7.0
  flutter_svg: ^0.22.0
#  firebase_core: ^0.4.5
#  firebase_messaging: ^6.0.16
  shimmer: ^1.1.1
  simple_animations: ^2.2.1
#  flutter_local_notifications: ^1.4.4+4
#  location: ^3.0.2
  change_app_package_name: ^0.1.2
#  cloud_firestore: ^0.13.7
  share: ^0.6.5
  provider: ^5.0.0
#  file_picker: ^1.13.3
  photo_view: ^0.10.2
  flutter_staggered_grid_view: ^0.3.2
  flutter_screenutil: ^4.0.2+5
  carousel_slider: ^2.3.1
  flutter_rating_bar: ^3.2.0+1
  loading_animations: ^2.1.0
  android_intent: ^0.3.6+12
#  geolocator: ^5.3.0
#  location_permissions: ^3.0.0+1
  intl_phone_number_input:
  get_storage:
  path_provider: ^2.0.1
  progress_dialog: ^1.2.4
  easy_localization: ^3.0.0
  get_it: ^3.0.0+1
  pin_code_fields:
  video_player:
  cached_network_image: ^3.0.0
#  permission_handler: ^5.0.1+1
  geocoder: ^0.2.1
  webview_flutter: ^2.0.8
  flutter_webview_plugin: ^0.3.10+1
  fluttertoast: ^7.1.5
  expansion_card: ^0.1.0
  expansion_tile_card: ^1.1.0
  conditional_builder: ^1.0.2
  page_view_indicators: ^2.0.0
  flutter_spinkit: ^3.1.0
  syncfusion_flutter_datepicker:
  flutter_xlider: ^3.4.0
  smooth_page_indicator: ^1.0.0+2
  extended_nested_scroll_view: ^4.0.0
  dotted_line: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/locales/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu/Ubuntu-Regular.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-Italic.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-Bold.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-BoldItalic.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-LightItalic.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-Medium.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-MediumItalic.ttf

    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-Regular.ttf
        - asset: assets/fonts/cairo/Cairo-Bold.ttf
        - asset: assets/fonts/cairo/Cairo-Light.ttf
        - asset: assets/fonts/cairo/HacenTunisia.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
